version: '2'
services:
  elasticsearch:
    image: elasticsearch:5
    volumes:
      - elk_db:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elk
    environment:
      ES_JAVA_OPTS: "-Xmx1g -Xms256m"

  logstash:
    build:
      context: ${PWD}/logstash
      dockerfile: Dockerfile
    image: nefariusmag/logstash:1.0.0
    volumes:
      - ${PWD}/logstash/:/etc/logstash/conf.d
    ports:
      - 5044:5044
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms256m"
    depends_on: ['elasticsearch']
    networks:
      - elk

  kibana:
    image: kibana:5
    ports:
      - 5601:5601
    depends_on: ['elasticsearch']
    networks:
      - elk

volumes:
  elk_db:

networks:
  elk:
    driver: bridge
